esphome:
  name: lounge_8266
  platform: ESP8266
  board: d1_mini
  includes:
    - toshiba.h
    - toshiba.cpp

wifi:
  ssid: ----
  password: ----

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ----

ota:
  password: ----
  
# Wemos IR controller shield  
remote_transmitter:
  pin: D3
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

remote_receiver:
  pin:
    number: D6
    inverted: True
  dump: all

climate:
  - platform: toshiba
    name: Lounge_Heatpump
  
